Fix package json
yarax/swagger-to-graphql pull request #85
Opened 2018-06-30 12:37 UTC by 0xR

Adds graphql as a peerDependency. Avoids issues with duplicate instances of GraphQL.
Adds repository field.
Replaces prePublish with a prepare scripts.

2018-06-30 12:43 UTC, yarax commented
Nice, thanks. What's the goal of replacing prepublish?

2018-06-30 13:50 UTC, 0xR commented
prepublish is depracated and building should happen in the new `prepare` script:
https://github.com/npm/npm/issues/10074

2018-06-30 13:54 UTC, yarax commented
I see, good to know!

2018-06-30 13:54 UTC, merged

2023-07-09 13:16 UTC, Darby101 requested changes

2023-07-09 13:16 UTC, Darby101 commented on package.json
> -    "graphql": "^0.12.3",
{
  "scripts": {
    "precompress": "{{ executes BEFORE the `compress` script }}",
    "compress": "{{ run command to compress files }}",
    "postcompress": "{{ executes AFTER `compress` script }}"
  }
}

2023-07-09 13:16 UTC, Darby101 commented on package.json
> -    "prepublish": "npm run build",
package.json

2025-03-28 01:40 UTC, Joe1the2Creator3 commented
{
  "scripts": {
    "precompress": "{{ executes BEFORE the `compress` script }}",
    "compress": "{{ run command to compress files }}",
    "postcompress": "{{ executes AFTER `compress` script }}"
  }
}

2026-01-27 22:55 UTC, bdstar81 approved these changes